// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: v2/hcore/icmpservice/icmp_service.proto

package icmpservice

import (
	context "context"
	hcommon "github.com/hiddify/hiddify-core/v2/hcommon"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IcmpService_OpenSession_FullMethodName  = "/icmpservice.IcmpService/OpenSession"
	IcmpService_ReadFrom_FullMethodName     = "/icmpservice.IcmpService/ReadFrom"
	IcmpService_WriteTo_FullMethodName      = "/icmpservice.IcmpService/WriteTo"
	IcmpService_SetDeadlines_FullMethodName = "/icmpservice.IcmpService/SetDeadlines"
	IcmpService_CloseSession_FullMethodName = "/icmpservice.IcmpService/CloseSession"
	IcmpService_Exit_FullMethodName         = "/icmpservice.IcmpService/Exit"
)

// IcmpServiceClient is the client API for IcmpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IcmpService lets an unprivileged process on Windows use xicmp's unprivileged ("dgram")
// ICMP mode, which the OS itself only allows to elevated (Administrator) processes. A separate,
// on-demand-elevated instance of HiddifyCli.exe hosts this service; the main (unelevated)
// process forwards ICMP reads/writes to it over loopback gRPC instead of opening the sockets
// itself. Every RPC is scoped to a session (one real OS ICMP socket per session, opened by
// OpenSession and released by CloseSession) so multiple xicmp outbounds can be proxied
// concurrently without sharing state.
type IcmpServiceClient interface {
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	ReadFrom(ctx context.Context, in *ReadFromRequest, opts ...grpc.CallOption) (*ReadFromResponse, error)
	WriteTo(ctx context.Context, in *WriteToRequest, opts ...grpc.CallOption) (*WriteToResponse, error)
	SetDeadlines(ctx context.Context, in *SetDeadlinesRequest, opts ...grpc.CallOption) (*hcommon.Empty, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*hcommon.Empty, error)
	Exit(ctx context.Context, in *hcommon.Empty, opts ...grpc.CallOption) (*hcommon.Empty, error)
}

type icmpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIcmpServiceClient(cc grpc.ClientConnInterface) IcmpServiceClient {
	return &icmpServiceClient{cc}
}

func (c *icmpServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, IcmpService_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icmpServiceClient) ReadFrom(ctx context.Context, in *ReadFromRequest, opts ...grpc.CallOption) (*ReadFromResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFromResponse)
	err := c.cc.Invoke(ctx, IcmpService_ReadFrom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icmpServiceClient) WriteTo(ctx context.Context, in *WriteToRequest, opts ...grpc.CallOption) (*WriteToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteToResponse)
	err := c.cc.Invoke(ctx, IcmpService_WriteTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icmpServiceClient) SetDeadlines(ctx context.Context, in *SetDeadlinesRequest, opts ...grpc.CallOption) (*hcommon.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(hcommon.Empty)
	err := c.cc.Invoke(ctx, IcmpService_SetDeadlines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icmpServiceClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*hcommon.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(hcommon.Empty)
	err := c.cc.Invoke(ctx, IcmpService_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *icmpServiceClient) Exit(ctx context.Context, in *hcommon.Empty, opts ...grpc.CallOption) (*hcommon.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(hcommon.Empty)
	err := c.cc.Invoke(ctx, IcmpService_Exit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IcmpServiceServer is the server API for IcmpService service.
// All implementations must embed UnimplementedIcmpServiceServer
// for forward compatibility.
//
// IcmpService lets an unprivileged process on Windows use xicmp's unprivileged ("dgram")
// ICMP mode, which the OS itself only allows to elevated (Administrator) processes. A separate,
// on-demand-elevated instance of HiddifyCli.exe hosts this service; the main (unelevated)
// process forwards ICMP reads/writes to it over loopback gRPC instead of opening the sockets
// itself. Every RPC is scoped to a session (one real OS ICMP socket per session, opened by
// OpenSession and released by CloseSession) so multiple xicmp outbounds can be proxied
// concurrently without sharing state.
type IcmpServiceServer interface {
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	ReadFrom(context.Context, *ReadFromRequest) (*ReadFromResponse, error)
	WriteTo(context.Context, *WriteToRequest) (*WriteToResponse, error)
	SetDeadlines(context.Context, *SetDeadlinesRequest) (*hcommon.Empty, error)
	CloseSession(context.Context, *CloseSessionRequest) (*hcommon.Empty, error)
	Exit(context.Context, *hcommon.Empty) (*hcommon.Empty, error)
	mustEmbedUnimplementedIcmpServiceServer()
}

// UnimplementedIcmpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIcmpServiceServer struct{}

func (UnimplementedIcmpServiceServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedIcmpServiceServer) ReadFrom(context.Context, *ReadFromRequest) (*ReadFromResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFrom not implemented")
}
func (UnimplementedIcmpServiceServer) WriteTo(context.Context, *WriteToRequest) (*WriteToResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteTo not implemented")
}
func (UnimplementedIcmpServiceServer) SetDeadlines(context.Context, *SetDeadlinesRequest) (*hcommon.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDeadlines not implemented")
}
func (UnimplementedIcmpServiceServer) CloseSession(context.Context, *CloseSessionRequest) (*hcommon.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedIcmpServiceServer) Exit(context.Context, *hcommon.Empty) (*hcommon.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Exit not implemented")
}
func (UnimplementedIcmpServiceServer) mustEmbedUnimplementedIcmpServiceServer() {}
func (UnimplementedIcmpServiceServer) testEmbeddedByValue()                     {}

// UnsafeIcmpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IcmpServiceServer will
// result in compilation errors.
type UnsafeIcmpServiceServer interface {
	mustEmbedUnimplementedIcmpServiceServer()
}

func RegisterIcmpServiceServer(s grpc.ServiceRegistrar, srv IcmpServiceServer) {
	// If the following call panics, it indicates UnimplementedIcmpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IcmpService_ServiceDesc, srv)
}

func _IcmpService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcmpServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IcmpService_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcmpServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IcmpService_ReadFrom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFromRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcmpServiceServer).ReadFrom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IcmpService_ReadFrom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcmpServiceServer).ReadFrom(ctx, req.(*ReadFromRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IcmpService_WriteTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcmpServiceServer).WriteTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IcmpService_WriteTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcmpServiceServer).WriteTo(ctx, req.(*WriteToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IcmpService_SetDeadlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeadlinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcmpServiceServer).SetDeadlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IcmpService_SetDeadlines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcmpServiceServer).SetDeadlines(ctx, req.(*SetDeadlinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IcmpService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcmpServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IcmpService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcmpServiceServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IcmpService_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hcommon.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IcmpServiceServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IcmpService_Exit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IcmpServiceServer).Exit(ctx, req.(*hcommon.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IcmpService_ServiceDesc is the grpc.ServiceDesc for IcmpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IcmpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "icmpservice.IcmpService",
	HandlerType: (*IcmpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _IcmpService_OpenSession_Handler,
		},
		{
			MethodName: "ReadFrom",
			Handler:    _IcmpService_ReadFrom_Handler,
		},
		{
			MethodName: "WriteTo",
			Handler:    _IcmpService_WriteTo_Handler,
		},
		{
			MethodName: "SetDeadlines",
			Handler:    _IcmpService_SetDeadlines_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _IcmpService_CloseSession_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _IcmpService_Exit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/hcore/icmpservice/icmp_service.proto",
}
