// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v2/hcore/icmpservice/icmp_service.proto

package icmpservice

import (
	hcommon "github.com/hiddify/hiddify-core/v2/hcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Family int32

const (
	Family_V4 Family = 0
	Family_V6 Family = 1
)

// Enum value maps for Family.
var (
	Family_name = map[int32]string{
		0: "V4",
		1: "V6",
	}
	Family_value = map[string]int32{
		"V4": 0,
		"V6": 1,
	}
)

func (x Family) Enum() *Family {
	p := new(Family)
	*p = x
	return p
}

func (x Family) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Family) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_hcore_icmpservice_icmp_service_proto_enumTypes[0].Descriptor()
}

func (Family) Type() protoreflect.EnumType {
	return &file_v2_hcore_icmpservice_icmp_service_proto_enumTypes[0]
}

func (x Family) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Family.Descriptor instead.
func (Family) EnumDescriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{0}
}

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        Family                 `protobuf:"varint,1,opt,name=family,proto3,enum=icmpservice.Family" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetFamily() Family {
	if x != nil {
		return x.Family
	}
	return Family_V4
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadFromRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFromRequest) Reset() {
	*x = ReadFromRequest{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFromRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFromRequest) ProtoMessage() {}

func (x *ReadFromRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFromRequest.ProtoReflect.Descriptor instead.
func (*ReadFromRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFromRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadFromRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ReadFromResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	AddrIp        string                 `protobuf:"bytes,2,opt,name=addr_ip,json=addrIp,proto3" json:"addr_ip,omitempty"` // source IP only - ICMP addressing has no port
	TimedOut      bool                   `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFromResponse) Reset() {
	*x = ReadFromResponse{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFromResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFromResponse) ProtoMessage() {}

func (x *ReadFromResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFromResponse.ProtoReflect.Descriptor instead.
func (*ReadFromResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFromResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFromResponse) GetAddrIp() string {
	if x != nil {
		return x.AddrIp
	}
	return ""
}

func (x *ReadFromResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *ReadFromResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteToRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	AddrIp        string                 `protobuf:"bytes,3,opt,name=addr_ip,json=addrIp,proto3" json:"addr_ip,omitempty"` // destination IP only - ICMP addressing has no port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteToRequest) Reset() {
	*x = WriteToRequest{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToRequest) ProtoMessage() {}

func (x *WriteToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToRequest.ProtoReflect.Descriptor instead.
func (*WriteToRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{4}
}

func (x *WriteToRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteToRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteToRequest) GetAddrIp() string {
	if x != nil {
		return x.AddrIp
	}
	return ""
}

type WriteToResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteToResponse) Reset() {
	*x = WriteToResponse{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToResponse) ProtoMessage() {}

func (x *WriteToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToResponse.ProtoReflect.Descriptor instead.
func (*WriteToResponse) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{5}
}

func (x *WriteToResponse) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *WriteToResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetDeadlinesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Each deadline needs 3 distinct states, not 2: "leave unchanged" (this setter wasn't
	// called - has_*_deadline false), "clear" (net.Conn.SetReadDeadline(time.Time{}), meaning
	// block forever - has_*_deadline true, clear_*_deadline true), and "set to an absolute time"
	// (has_*_deadline true, clear_*_deadline false, *_deadline_unix_nano holds
	// time.Time.UnixNano()). A zero time.Time{} does NOT UnixNano() to 0 (it's year 1, not the
	// Unix epoch) and does not survive a UnixNano()/time.Unix() round-trip back to something
	// IsZero() reports true for - so "clear" must be its own explicit flag, not inferred from a
	// zero nanosecond value, or a real "no deadline" request would silently become "deadline
	// already expired in 1970" and every subsequent read would fail instantly.
	HasReadDeadline       bool  `protobuf:"varint,2,opt,name=has_read_deadline,json=hasReadDeadline,proto3" json:"has_read_deadline,omitempty"`
	ClearReadDeadline     bool  `protobuf:"varint,3,opt,name=clear_read_deadline,json=clearReadDeadline,proto3" json:"clear_read_deadline,omitempty"`
	ReadDeadlineUnixNano  int64 `protobuf:"varint,4,opt,name=read_deadline_unix_nano,json=readDeadlineUnixNano,proto3" json:"read_deadline_unix_nano,omitempty"`
	HasWriteDeadline      bool  `protobuf:"varint,5,opt,name=has_write_deadline,json=hasWriteDeadline,proto3" json:"has_write_deadline,omitempty"`
	ClearWriteDeadline    bool  `protobuf:"varint,6,opt,name=clear_write_deadline,json=clearWriteDeadline,proto3" json:"clear_write_deadline,omitempty"`
	WriteDeadlineUnixNano int64 `protobuf:"varint,7,opt,name=write_deadline_unix_nano,json=writeDeadlineUnixNano,proto3" json:"write_deadline_unix_nano,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetDeadlinesRequest) Reset() {
	*x = SetDeadlinesRequest{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeadlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeadlinesRequest) ProtoMessage() {}

func (x *SetDeadlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeadlinesRequest.ProtoReflect.Descriptor instead.
func (*SetDeadlinesRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetDeadlinesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetDeadlinesRequest) GetHasReadDeadline() bool {
	if x != nil {
		return x.HasReadDeadline
	}
	return false
}

func (x *SetDeadlinesRequest) GetClearReadDeadline() bool {
	if x != nil {
		return x.ClearReadDeadline
	}
	return false
}

func (x *SetDeadlinesRequest) GetReadDeadlineUnixNano() int64 {
	if x != nil {
		return x.ReadDeadlineUnixNano
	}
	return 0
}

func (x *SetDeadlinesRequest) GetHasWriteDeadline() bool {
	if x != nil {
		return x.HasWriteDeadline
	}
	return false
}

func (x *SetDeadlinesRequest) GetClearWriteDeadline() bool {
	if x != nil {
		return x.ClearWriteDeadline
	}
	return false
}

func (x *SetDeadlinesRequest) GetWriteDeadlineUnixNano() int64 {
	if x != nil {
		return x.WriteDeadlineUnixNano
	}
	return 0
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_hcore_icmpservice_icmp_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP(), []int{7}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_v2_hcore_icmpservice_icmp_service_proto protoreflect.FileDescriptor

const file_v2_hcore_icmpservice_icmp_service_proto_rawDesc = "" +
	"\n" +
	"'v2/hcore/icmpservice/icmp_service.proto\x12\vicmpservice\x1a\x17v2/hcommon/common.proto\"A\n" +
	"\x12OpenSessionRequest\x12+\n" +
	"\x06family\x18\x01 \x01(\x0e2\x13.icmpservice.FamilyR\x06family\"J\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x0fReadFromRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x05R\bmaxBytes\"r\n" +
	"\x10ReadFromResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\aaddr_ip\x18\x02 \x01(\tR\x06addrIp\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\\\n" +
	"\x0eWriteToRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\aaddr_ip\x18\x03 \x01(\tR\x06addrIp\"5\n" +
	"\x0fWriteToResponse\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xe0\x02\n" +
	"\x13SetDeadlinesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x11has_read_deadline\x18\x02 \x01(\bR\x0fhasReadDeadline\x12.\n" +
	"\x13clear_read_deadline\x18\x03 \x01(\bR\x11clearReadDeadline\x125\n" +
	"\x17read_deadline_unix_nano\x18\x04 \x01(\x03R\x14readDeadlineUnixNano\x12,\n" +
	"\x12has_write_deadline\x18\x05 \x01(\bR\x10hasWriteDeadline\x120\n" +
	"\x14clear_write_deadline\x18\x06 \x01(\bR\x12clearWriteDeadline\x127\n" +
	"\x18write_deadline_unix_nano\x18\a \x01(\x03R\x15writeDeadlineUnixNano\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId*\x18\n" +
	"\x06Family\x12\x06\n" +
	"\x02V4\x10\x00\x12\x06\n" +
	"\x02V6\x10\x012\x9a\x03\n" +
	"\vIcmpService\x12P\n" +
	"\vOpenSession\x12\x1f.icmpservice.OpenSessionRequest\x1a .icmpservice.OpenSessionResponse\x12G\n" +
	"\bReadFrom\x12\x1c.icmpservice.ReadFromRequest\x1a\x1d.icmpservice.ReadFromResponse\x12D\n" +
	"\aWriteTo\x12\x1b.icmpservice.WriteToRequest\x1a\x1c.icmpservice.WriteToResponse\x12@\n" +
	"\fSetDeadlines\x12 .icmpservice.SetDeadlinesRequest\x1a\x0e.hcommon.Empty\x12@\n" +
	"\fCloseSession\x12 .icmpservice.CloseSessionRequest\x1a\x0e.hcommon.Empty\x12&\n" +
	"\x04Exit\x12\x0e.hcommon.Empty\x1a\x0e.hcommon.EmptyBa\n" +
	")com.hiddify.core.api.v2.hcore.icmpserviceZ4github.com/hiddify/hiddify-core/v2/hcore/icmpserviceb\x06proto3"

var (
	file_v2_hcore_icmpservice_icmp_service_proto_rawDescOnce sync.Once
	file_v2_hcore_icmpservice_icmp_service_proto_rawDescData []byte
)

func file_v2_hcore_icmpservice_icmp_service_proto_rawDescGZIP() []byte {
	file_v2_hcore_icmpservice_icmp_service_proto_rawDescOnce.Do(func() {
		file_v2_hcore_icmpservice_icmp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_hcore_icmpservice_icmp_service_proto_rawDesc), len(file_v2_hcore_icmpservice_icmp_service_proto_rawDesc)))
	})
	return file_v2_hcore_icmpservice_icmp_service_proto_rawDescData
}

var file_v2_hcore_icmpservice_icmp_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v2_hcore_icmpservice_icmp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v2_hcore_icmpservice_icmp_service_proto_goTypes = []any{
	(Family)(0),                 // 0: icmpservice.Family
	(*OpenSessionRequest)(nil),  // 1: icmpservice.OpenSessionRequest
	(*OpenSessionResponse)(nil), // 2: icmpservice.OpenSessionResponse
	(*ReadFromRequest)(nil),     // 3: icmpservice.ReadFromRequest
	(*ReadFromResponse)(nil),    // 4: icmpservice.ReadFromResponse
	(*WriteToRequest)(nil),      // 5: icmpservice.WriteToRequest
	(*WriteToResponse)(nil),     // 6: icmpservice.WriteToResponse
	(*SetDeadlinesRequest)(nil), // 7: icmpservice.SetDeadlinesRequest
	(*CloseSessionRequest)(nil), // 8: icmpservice.CloseSessionRequest
	(*hcommon.Empty)(nil),       // 9: hcommon.Empty
}
var file_v2_hcore_icmpservice_icmp_service_proto_depIdxs = []int32{
	0, // 0: icmpservice.OpenSessionRequest.family:type_name -> icmpservice.Family
	1, // 1: icmpservice.IcmpService.OpenSession:input_type -> icmpservice.OpenSessionRequest
	3, // 2: icmpservice.IcmpService.ReadFrom:input_type -> icmpservice.ReadFromRequest
	5, // 3: icmpservice.IcmpService.WriteTo:input_type -> icmpservice.WriteToRequest
	7, // 4: icmpservice.IcmpService.SetDeadlines:input_type -> icmpservice.SetDeadlinesRequest
	8, // 5: icmpservice.IcmpService.CloseSession:input_type -> icmpservice.CloseSessionRequest
	9, // 6: icmpservice.IcmpService.Exit:input_type -> hcommon.Empty
	2, // 7: icmpservice.IcmpService.OpenSession:output_type -> icmpservice.OpenSessionResponse
	4, // 8: icmpservice.IcmpService.ReadFrom:output_type -> icmpservice.ReadFromResponse
	6, // 9: icmpservice.IcmpService.WriteTo:output_type -> icmpservice.WriteToResponse
	9, // 10: icmpservice.IcmpService.SetDeadlines:output_type -> hcommon.Empty
	9, // 11: icmpservice.IcmpService.CloseSession:output_type -> hcommon.Empty
	9, // 12: icmpservice.IcmpService.Exit:output_type -> hcommon.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v2_hcore_icmpservice_icmp_service_proto_init() }
func file_v2_hcore_icmpservice_icmp_service_proto_init() {
	if File_v2_hcore_icmpservice_icmp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_hcore_icmpservice_icmp_service_proto_rawDesc), len(file_v2_hcore_icmpservice_icmp_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_hcore_icmpservice_icmp_service_proto_goTypes,
		DependencyIndexes: file_v2_hcore_icmpservice_icmp_service_proto_depIdxs,
		EnumInfos:         file_v2_hcore_icmpservice_icmp_service_proto_enumTypes,
		MessageInfos:      file_v2_hcore_icmpservice_icmp_service_proto_msgTypes,
	}.Build()
	File_v2_hcore_icmpservice_icmp_service_proto = out.File
	file_v2_hcore_icmpservice_icmp_service_proto_goTypes = nil
	file_v2_hcore_icmpservice_icmp_service_proto_depIdxs = nil
}
